# Generated by Django 4.0.5 on 2022-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cash_payment_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'waiter'), (2, 'cashier'), (3, 'director'), (4, 'manager')], default=1),
        ),
    ]
